version: "3.8"

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      # UDP Tracing Jaeger
      - "6831:6831/udp"
      # UI
      - "16686:16686"
      # HTTP Tracing instrad of UDP
      - "14250"
      # GRPC
      - "14268:14268"

  localstack:
    container_name: "localstack"
    image: localstack/localstack:latest
    ports:
      - "0.0.0.0:4566:4566"
      - "0.0.0.0:4571:4571"
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID="test"
      - AWS_SECRET_ACCESS_KEY="test"
      - SERVICES=sqs,kms
      - DATA_DIR="./data"
      - HOST_TMP_FOLDER=${TMPDIR:-/tmp/}localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - './scripts/init.sh:/docker-entrypoint-initaws.d/init.sh'

  credit-score-service:
    build: ./credit-score-service
    restart: on-failure
    environment:
      - AWS_ACCESS_KEY_ID=XXXXXXXXXXXX
      - AWS_SECRET_ACCESS_KEY=XXXXXXXXX
      - AWS_REGION=us-east-1
      - ENDPOINT_URL=http://localstack:4566
      - CREDIT_SCORE_REQUESTS_QUEUE_NAME=credit-score-requests
      - CREDIT_SCORE_RESPONSES_QUEUE_NAME=credit-score-responses
      - BANKING_REQUESTS_QUEUE_NAME=banking-requests
      - BANKING_RESPONSES_QUEUE_NAME=banking-responses
      - JAEGER_ENDPOINT=http://jaeger:14268/api/traces
    ports:
      - 8080:8080
    depends_on:
      localstack:
        condition: service_started

  banking-gateway:
    build: ./banking-gateway
    restart: on-failure
    environment:
      - AWS_ACCESS_KEY_ID=XXXXXXXXXXXX
      - AWS_SECRET_ACCESS_KEY=XXXXXXXXX
      - AWS_REGION=us-east-1
      - ENDPOINT_URL=http://localstack:4566
      - BANKING_REQUESTS_QUEUE_NAME=banking-requests
      - BANKING_RESPONSES_QUEUE_NAME=banking-responses
      - JAEGER_ENDPOINT=http://jaeger:14268/api/traces
    depends_on:
      localstack:
        condition: service_started
